CREATE TABLE TB_EMPRESA_AEROESPACIAL (
    ID_EMPRESA NUMBER(10) PRIMARY KEY,
    CNPJ_ID_EMPRESA NVARCHAR2(20) NOT NULL,
    NOME_EMPRESA NVARCHAR2(100) NOT NULL,
    PAIS_ORIGEM NVARCHAR2(50) NOT NULL,
    STATUS_OPERACAO NVARCHAR2(20) NOT NULL
);

CREATE TABLE TB_CHASER (
    ID_CHASER NUMBER(10) PRIMARY KEY,
    NUM_BATERIA DECIMAL(18, 2) NOT NULL,
    COORDENADA_Z DECIMAL(18, 4) NOT NULL,
    TXT_COORDENADA_Y DECIMAL(18, 2) NOT NULL,
    TXT_COORDENADA_Z DECIMAL(18, 2) NOT NULL,
    NOME_CHASER NVARCHAR2(50) NOT NULL
);

CREATE TABLE TB_DETRITO_ESPACIAL (
    ID_DETRITO NUMBER(10) PRIMARY KEY,
    TXT_COORDENADA_X DECIMAL(18, 2) NOT NULL,
    TXT_COORDENADA_Y DECIMAL(18, 2) NOT NULL,
    TXT_COORDENADA_Z DECIMAL(18, 2) NOT NULL,
    MASSA_KG DECIMAL(18, 4) NOT NULL,
    NOME_DETRITO NVARCHAR2(100) NOT NULL,
    TAMANHO_METROS DECIMAL(18, 2) NOT NULL
);

CREATE TABLE TB_SATELITE (
    ID_SATELITE NUMBER(10) PRIMARY KEY,
    NUMERO_ALTITUDE_KM DECIMAL(18, 2) NOT NULL,
    ID_EMPRESA NUMBER(10) NOT NULL,
    NUMERO_SATELITE NVARCHAR2(100) NOT NULL,
    CONSTRAINT FK_SAT_EMP FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA_AEROESPACIAL(ID_EMPRESA) ON DELETE CASCADE
);

CREATE TABLE TB_ALERTA_COLISAO (
    ID_ALERTA NUMBER(10) PRIMARY KEY,
    DetritoEspacialId NUMBER(10),
    ID_DETRITO NUMBER(10) NOT NULL,
    ID_SATELITE NUMBER(10) NOT NULL,
    STATUS_GRAVIDADE NVARCHAR2(20) NOT NULL,
    CONSTRAINT FK_ALE_DET FOREIGN KEY (ID_DETRITO) REFERENCES TB_DETRITO_ESPACIAL(ID_DETRITO) ON DELETE CASCADE,
    CONSTRAINT FK_ALE_SAT FOREIGN KEY (ID_SATELITE) REFERENCES TB_SATELITE(ID_SATELITE) ON DELETE CASCADE
);

CREATE TABLE TB_MISSAO_INTERCEPTACAO (
    ID_MISSAO NUMBER(10) PRIMARY KEY,
    ID_ALERTA NUMBER(10) NOT NULL,
    ID_CHASER NUMBER(10) NOT NULL,
    DATA_EXECUCAO TIMESTAMP(7) NOT NULL,
    STATUS_MISSAO NVARCHAR2(20) NOT NULL,
    CONSTRAINT FK_MIS_ALE FOREIGN KEY (ID_ALERTA) REFERENCES TB_ALERTA_COLISAO(ID_ALERTA) ON DELETE CASCADE,
    CONSTRAINT FK_MIS_CHA FOREIGN KEY (ID_CHASER) REFERENCES TB_CHASER(ID_CHASER) ON DELETE CASCADE
);

COMMIT;